- name: Basic Linux Server Setup
  hosts: linux
  become: yes

  tasks:
    - name: Install packages
      yum:
        name:
          - git
          - docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true